// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7iOm_jqAQLVl0j4wTz-TSBBXqLWl2ExU',
    appId: '1:1038785403105:android:c9ca948da7ef7b6f387fa0',
    messagingSenderId: '1038785403105',
    projectId: 'revise123422',
    storageBucket: 'revise123422.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI9WiGoh-fTpEYFSizkE3LLJy-Uh5woRg',
    appId: '1:1038785403105:ios:f968ca0ce10fe0ba387fa0',
    messagingSenderId: '1038785403105',
    projectId: 'revise123422',
    storageBucket: 'revise123422.appspot.com',
    androidClientId: '1038785403105-b47352fmih0rnf82vbvlsdnhgsjovau8.apps.googleusercontent.com',
    iosClientId: '1038785403105-s1fmulh16d15otvra9cronh4prmnan45.apps.googleusercontent.com',
    iosBundleId: 'com.revise.mobile',
  );
}
